### ISSUE TITLE
No module named 'distutils' error during installation on Python 3.12

### ISSUE THREAD

**Issue by userofwireless** [utcsilab/diffusion-channels#8]
https://docs.python.org/3.10/library/distutils.html

Per the above link, distutils module has been removed in Python 3.12. 

This is causing error during installation.

**Comment by mariusarvinte** [comment]
Hello, currently we only support up to Python 3.10 (possibly 3.11 too, but untested) due to incompatibility with PyTorch 2.0.0 `pip` wheels. I've added some clearer instructions in https://github.com/utcsilab/score-based-channels/commit/46e16038c80ca25352131336c6691a84198b538e.

I will try to update all packages to newer versions but it will require more testing before release.

**Comment by userofwireless** [comment]
Thank you for the note and the link to the instructions. Very helpful. I will use one of the supported Python versions.

**Comment by mariusarvinte** [comment]
Fixed in #9, Python3.12 compatibility is now enabled. Feel free to re-open if you find other issues related to this.
